---
- hosts: all
  become: true
  vars:
    hostname: "dev"
    dbuser: "root"
    dbpasswd: "password"
    databases: []
    sites: []
    php_modules: ['php7.3-mysql', 'php7.3-gd', 'php-apcu', 'php7.3-curl', 'php7.3-intl', 'php-memcached', 'php7.3-mbstring', 'php7.3-xml', 'php7.3-pgsql', 'php7.3-dev']
    install_db: "no"
    install_web: "no"
    install_ohmyzsh: "no"
    install_beanstalkd: "no"
    install_redis: "no"
    install_javascript_build_system: "no"
    install_gems: []
    php_configs: []
    install_postgresql: "no"
    postgresql_version: "9.5"
    postgresql_user: "root"
    postgresql_passwd: "password"
    postgresql_databases: []
    enable_swap: "yes"
    swap_size_in_mb: 1024
    install_rabbit_mq: "no"
  tasks:
    - include: tasks/system.yml
    - include: tasks/ohmyzsh.yml
      when: install_ohmyzsh == "yes"
    - include: tasks/mysql.yml
      when: install_db == "yes"
    - include: tasks/php.yml
      when: install_web == "yes"
    - include: tasks/php-fpm.yml
      when: install_web == "yes"
    - include: tasks/nginx.yml
      when: install_web == "yes"
    - include: tasks/beanstalkd.yml
      when: install_beanstalkd == "yes"
    - include: tasks/nodejs.yml
      when: install_javascript_build_system == "yes"
    - include: tasks/redis.yml
      when: install_redis == "yes"
    - include: tasks/ruby.yml
    - include: tasks/swap.yml
      when: enable_swap == "yes"
    - include: tasks/postgresql.yml
      when: install_postgresql == "yes"
    - include: tasks/rabbitmq.yml
      when: install_rabbit_mq == "yes"
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart php7.3-fpm
      service: name=php7.3-fpm state=restarted
    - name: restart mysql
      service: name=mysql state=restarted