---
- hosts: all
  sudo: true
  vars:
    hostname: "dev"
    dbuser: "root"
    dbpasswd: "password"
    databases: []
    sites: []
    install_swapfile: "no"
    install_db: "no"
    install_web: "no"
    install_ohmyzsh: "no"
    install_hhvm: "no"
    install_mailcatcher: "no"
    install_beanstalkd: "no"
    install_redis: "no"
    install_javascript_build_system: "no"
    install_gems: []
    install_r: "no"
    r_packages: []
    install_java: "no"
    install_scala: "no"
    scala_activator_version: "1.2.10"
  tasks:
    - include: tasks/system.yml
    - include: tasks/swapfile.yml
      when: install_swapfile == "yes"
    - include: tasks/ohmyzsh.yml
      when: install_ohmyzsh == "yes"
    - include: tasks/mysql.yml
      when: install_db == "yes"
    - include: tasks/php.yml
      when: install_web == "yes"
    - include: tasks/php-fpm.yml
      when: install_web == "yes"
    - include: tasks/nginx.yml
      when: install_web == "yes"
    - include: tasks/hhvm.yml
      when: install_hhvm == "yes"
    - include: tasks/mailcatcher.yml
      when: install_mailcatcher == "yes"
    - include: tasks/beanstalkd.yml
      when: install_beanstalkd == "yes"
    - include: tasks/nodejs.yml
      when: install_javascript_build_system == "yes"
    - include: tasks/redis.yml
      when: install_redis == "yes"
    - include: tasks/ruby.yml
    - include: tasks/r.yml
      when: install_r == "yes"
    - include: tasks/java.yml
      when: install_java == "yes"
    - include: tasks/scala.yml
      when: install_scala == "yes"
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart php5-fpm
      service: name=php5-fpm state=restarted
    - name: restart mysql
      service: name=mysql state=restarted
