---

- name: lazygit | Install PPA
  apt_repository: repo='ppa:lazygit-team/release' update_cache=yes

- name: lazygit | Install lazygit
  apt:
    name: lazygit
    state: latest
    update_cache: yes