---
# Node.js

- name: Node.js | Install Node.js Repository
  shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

- name: Node.js | Install Node.js
  apt: pkg=nodejs state=latest

- name: Node.js | Install Yarn Repository key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Node.js | Install Yarn Repository
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    state: present
    update_cache: yes

- name: Node.js | INstall Yarn
  apt: pkg=yarn state=latest
