---
# PHP

- name: PHP | Install Ondrej PHP PPA
  apt_repository: repo='ppa:ondrej/php' update_cache=yes

- name: PHP | Install PHP 7.3
  apt: pkg=php7.3 state=latest
  tags: common

- name: PHP | Install PHP Modules
  apt:
    name: "{{php_modules}}"
    state: latest

# Composer

- stat: path=/usr/local/bin/composer
  register: composer_folder

- name: PHP | Install Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp
    mode: 0440

- name: PHP | Install Composer
  shell: php /tmp/installer && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  when: composer_folder.stat.isdir is not defined

# Update PHP.ini

- name: PHP | Install Custom PHP.ini Configurations for CLI PHP
  ini_file: dest=/etc/php/7.3/cli/php.ini
            section=PHP
            option="{{ item.option }}"
            value="{{ item.value }}"
            backup=yes
  with_items: "{{php_configs}}"
