---
# Redis

#- name: Redis | Install Redis PPA
#  apt_repository: repo='ppa:chris-lea/redis-server' update_cache=yes

- name: Redis | Install Redis
  apt: pkg=redis state=latest force=yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic' or ansible_distribution_release == 'focal'

- name: Redis | Install Redis
  apt: pkg=redis-server state=latest force=yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: Redis | Enable with Systemd
  systemd:
    name: redis
    enabled: yes
    state: started

#- name: Redis | Boot on Startup
#  service:
#    name: redis-server
#    enabled: yes
#    state: started